### PR TITLE
SpeedBoost block for Google Code-In task

### PR DESCRIPTION
**Pull request by BenjaminAmos**
The blocks give you a push in the direction of the arrow on the top which can be changed by interacting with it. Whilst the forces are not additive to each other, they could be considered to act a little more like a conveyer belt when put in a chain.

The block can be given to you by using the command:
`give SpeedBoost`

The direction labled in the code as player direction or direction number 4 is not used currently but its function is to propel the player across the block in the direction that he is current moving in.

### CODE REVIEW

**Comment by xrtariq2594** [comment]
Alright, I tested this one out @BenjaminAmos, and it looks great!

I have one question though. When the SpeedBlock is first placed onto the world and is not interacted with, if a player jumps on it, it will launch them straight up into the air (like a jump pad). Once a player interacts with it at least once, this doesn't happen anymore. Was that intentional?

**Comment by BenjaminAmos** [comment]
No, I do not believe that was intentional as I had not found this behavior whilst testing. Whilst I have tested jumping on it before, this has never happened to me. I will look into it later.

**Comment by BenjaminAmos** [comment]
I have looked into the issue about the block thrusting the player upwards, however i cannot reproduce it on my machine. If you have any ideas about the cause of it then please let me know and I will investigate further.

**Comment by xrtariq2594** [comment]
Here's what I did to get this odd behavior:

* Start Terasology
* Create a new world with just the FunnyBlocks module enabled.
* Use the console to spawn the SpeedBoost block.
* Place one on the ground.
* Jump on top of it.

Following that last step, I would be propelled into the air.

**Comment by BenjaminAmos** [comment]
Even whilst following your steps exactly, I cannot seem to find the behaviour that you are specifing. To show this, I have attached a low quality video file showing what I get when following your instructions in the zip linked below (hosted on github).
[SpeedBoost block bug.zip](https://github.com/Terasology/FunnyBlocks/files/628309/SpeedBoost.block.bug.zip)

**Pull request merged**
